### ISSUE TITLE
More than one extra target

### ISSUE THREAD

**Issue by GrayJack** [actions-rs/toolchain#52]
There is a feature to add mora than one extra target? If there is, how to set up?

**Comment by svartalf** [comment]
There is none, as so far I think this would a really rare case to support it out of box.

As long as you will "use" this Action, you will be guaranteed to have `rustup` in your `PATH`, so you can just add an extra [`run`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun) step to install additional target with `rustup target add {your-target}` command in it.

**Comment by svartalf** [comment]
UPD: I believe you want to solve [this problem](https://github.com/GrayJack/coreutils/blob/master/.github/workflows/fuchsia.yml#L22)? Alternatively, you can [include](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build) this target into the build matrix, but that would mean a separate full build

**Comment by GrayJack** [comment]
Yeah, I end up running the command since rustup was in path. Thanks for the help :smile:

**Comment by clauswilke** [comment]
Just came across this issue and wanted to point out that this is not that rare of a situation. There's an increasing number of people wanting to use Rust with R (e.g.: https://github.com/extendr/extendr), and all R packages that want to include Rust code will require two targets. This is because R by default builds both 32-bit and 64-bit binaries on Windows, in a single build. See e.g. here: https://github.com/clauswilke/sinab#installation

I expect I'll be able to use the `rustup` call, as described in the comment, but being able to specify two targets at once would make the build scripts much cleaner and simpler.
